### PR TITLE
Ensure that text box gets focus when the placeholder text is clicked.

### LINKED ISSUE #142: Textfield doesn't get focus when the user clicks it directly on the placeholder text
In TextField.ts, the _addListeners() method needs to be changed to add the code below that is either bolder or between two pairs of asterisks depending on whether Markdown syntax is working on GitHub today). Without this, the text field doesn't get focus when the user clicks it directly on the placeholder text. 

```typescript
if (this._type.indexOf(TextFieldConsts.Type.Placeholder) >= 0) {
        this._textField.addEventListener("focus", (event: MouseEvent) => {
          this._textFieldLabel.style.display = "none";
        });
	**// Ensure that the text box gets focus when the placeholder text itself is clicked.
        this._textFieldLabel.addEventListener("click", (event: MouseEvent) => {
          this._textField.focus();
        });**
        this._textField.addEventListener("blur", (event: MouseEvent) => {
          // Show only if no value in the text field
          if (this._textField.value.length === 0) {
            this._textFieldLabel.style.display = "block";
          }
        });
      }
```

Sorry, I can't make pull request because when I try to fork this repo, I get an erroneous message saying that I've already forked it.

### PR DESCRIPTION
**Pull request by Rick-Kirkham**
Without this change, the user has to click to the right of the placeholder text in order to give the text box focus and enter something in it. If user clicks on the part of the text box with the placeholder text, nothing happens; the text box appears to be broken.

This fixes #142

### CODE REVIEW

**Comment by Jahnp** [comment]
Thanks for the fix, @Rick-Kirkham! This fix looks great. I left one small note regarding the indentation of a comment--otherwise I'd say this is ready to go.

**Comment by mikewheaton** [comment]
Approved ⚡️

**Comment by Jahnp** [comment]
Approved 👍

**Comment by Jahnp** [comment]
Hi @Rick-Kirkham, sorry for the delay here. It looks like your branch is now out-of-date with `master`--would you mind updating it to the latest? Once that's done, we'd be happy to merge this in asap. Thanks so much!

**Comment by ericthompson** [comment]
@Rick-Kirkham - it looks like that indentation issue is causing the build to fail. Once you get that fixed up, builds should succeed and you'll be good to merge 👍 

Thanks for submitting a PR here!

image
then later...
image

**Comment by ericthompson** [comment]
Fixed by #163 using your work, Ricky - thanks for the help!

**Pull request closed without merging**
