### PR TITLE
Updated version numbers

### PR DESCRIPTION
**Pull request by Reezaali**

### CODE REVIEW

**Comment by mikewheaton** [comment]
Approved

**Comment by Jahnp** [comment]
Approved

**Comment by ericthompson** [comment]
@Reezaali - the [PR here](https://github.com/OfficeDev/office-ui-fabric-js/pull/223) makes similar adjustments but also removes the "Latest on CDN" portion since they're now in sync 😄

**Comment by mikewheaton** [comment]
Let's go ahead and use Eric's PR (#223). It also turns out that Fabric JS 1.2.0 uses Fabric Core 4.0.0, and I've made a comment in Eric's PR to update that.

**Pull request closed without merging**
