### PR TITLE
README: Add reference to Fabric JS

### PR DESCRIPTION
**Pull request by mikewheaton**
Adds a reference to Fabric JS in the code sample.

### CODE REVIEW

**Comment by Reezaali** [comment]
@mikewheaton - Looks good. Table in the README should also be updated.

**Comment by ericthompson** [comment]
Approved

**Comment by ericthompson** [comment]
Do we want to consider dropping the table soon? Especially now that we're on the new CDN 😄

**Comment by mikewheaton** [comment]
@ericthompson: Actually, let's just do that now. I'll add a note that releases generally make it to the CDN within a week.

**Comment by Reezaali** [comment]
Looks great @mikewheaton

**Comment by ericthompson** [comment]
Awesome - thanks!

Now enjoy your Thanksgiving 🦃

**Comment by battletoilet** [comment]
Approved

**Comment by Jahnp** [comment]
Approved

**Comment by Jahnp** [comment]
So much approval!

**Pull request merged**
