### PR TITLE
Checkbox not working within a Pivot

### PR DESCRIPTION
**Pull request by ericivarsson**
I ran into a problem where input type="checkbox" wasn´t working inside of a Pivot because of the onClick eventListener.
Not sure if this is the best way to solve the problem but it does seem to work fine for me.

### CODE REVIEW

**Comment by wdo3650** [comment]
Approved. Thanks @ericivarsson. I was able to repro the issue and keeping the onClick listener contained to ms-Pivot-links fixes the issue.

**Comment by mikewheaton** [comment]
Approved

**Comment by wdo3650** [comment]
@ericivarsson this PR is unable to be merge because the base branch is out of date. Can you merge the latest changes from master into your fork?

**Comment by ericivarsson** [comment]
@wdo3650 Sorry for the delay, I´ve updated the branch.

**Pull request merged**
