### PR TITLE
Bump to latest fabric-core version

### PR DESCRIPTION
**Pull request by philworthington**
Icon updates such as presence are included in 3.1.0 and need to be consumed for the js component to be viewed properly.

### CODE REVIEW

**Comment by mikewheaton** [comment]
3.2.0 will be out soon, and this will include all of the icons that are currently on the CDN.

**Comment by mikewheaton** [comment]
Fabric Core 4.0.0 is now available via NPM. 😄

**Comment by philworthington** [comment]
Updated with 4.0.0

**Comment by philworthington** [comment]
@mikewheaton Approve this now

**Comment by mikewheaton** [comment]
Approved by me 🉑

**Comment by ericthompson** [comment]
Approved

**Pull request merged**
