### PR TITLE
Leddie24/remove fabric core builds

### PR DESCRIPTION
**Pull request by leddie24**
Hi team, I removed all fabric core builds from the office fabric js repo and added them as a bower dependency instead.  Below is an overview of the list of changes that are included in this PR.

## List of Changes

1. Remove all Fabric core gulp tasks/files from Fabric JS repo
2. Adds bower dependency for office-ui-fabric-core (3.0.0)
3. SCSS references to fabric core files are pointing to bower_components/office-ui-fabric/ instead
4. Added Github link to top of menu of localhost documentation
5. Cleaned up some Gulp nuke tasks that weren't deleting directories
6. Deleted unused template (individual-component-example.html) Note: I couldn't find this being used, correct me if I'm mistaken!
7.  Added new paths to gulp config for pointing to bower_components/office-ui-fabric
8. Added bower as a build requirement in BUILDING.md

### CODE REVIEW

**Comment by mikewheaton** [comment]
Thanks for doing this, @leddie24! The [NPM package for Fabric Core 3.0](https://www.npmjs.com/package/office-ui-fabric-core) was published yesterday. Should we update this to use NPM rather than Bower? Thoughts, @battletoilet?

**Comment by battletoilet** [comment]
Yeah we should, @leddie24 is taking care of that now.

**Comment by leddie24** [comment]
All set! Ready for review again.

**Comment by battletoilet** [comment]
Approved

**Comment by mikewheaton** [comment]
Approved 🐰

**Pull request merged**
