### PR TITLE
Update Bower, NuGet, and NPM package info

### PR DESCRIPTION
**Pull request by mikewheaton**
This PR updates the package info for Bower, NuGet, and NPM to match what was included in the [1.0.0 release](https://github.com/OfficeDev/office-ui-fabric-js/releases/tag/1.0.0). No functional changes.

### CODE REVIEW

**Comment by philworthington** [comment]
The banners need to be updated as well.
https://github.com/OfficeDev/office-ui-fabric-js/blob/miwhea/1.0.0-changes/gulp/modules/Banners.js#L24

**Comment by mikewheaton** [comment]
Thanks, Phil, I've updated the PR.

**Comment by philworthington** [comment]
Approved

**Comment by ericthompson** [comment]
Approved

**Pull request merged**
