### PR TITLE
Fix ContextualHost position for left and top direction

### PR DESCRIPTION
**Pull request by GageAmes**
When calculating the position of the ContextualHost for the left and top
direction, the space occupied by the beak (arrowSpace) should be
subtracted instead of added to prevent the host from overlapping with the
target element.

Before:  https://plnkr.co/pILtwivmCjY4rPc5dPLm
After:  https://plnkr.co/pjUlvxrVUjZTP6fYsQwG

### CODE REVIEW

**Comment by mikewheaton** [comment]
Approved! Thanks for this contribution, @GageAmes, and for the detailed repro and demo of the fix.

**Comment by GageAmes** [comment]
Sorry for adding a new commit after your approval, @mikewheaton.  I didn't see it before I pushed.  Can you also take a look at my second fix for the top/bottom arrow or would you rather I back it out and create a new pull request?

For second fix:
Before:  https://plnkr.co/kretQFzjKV03a0hy0muf
After:  https://plnkr.co/1NME9MpLwH6NP8FG578Z

**Comment by mikewheaton** [comment]
Thanks for the additional fix, there's no need for a second pull request. 😄

**Comment by Jahnp** [comment]
Approved

Thanks @GageAmes! This is a great fix--really appreciate the contribution here :)

**Pull request merged**
