### PR TITLE
Updating chevron css classes for MessageBanner (Fixing #205)

### PR DESCRIPTION
**Pull request by FSc21**
In `MessageBanner.ts ` the chevron css class names are now correctly linked to the current set of icons from `fabric.css`
chevrons_fabric css

### CODE REVIEW

**Comment by mikewheaton** [comment]
Approved. Thank you, @FSc21!

**Comment by Jahnp** [comment]
Hi @FSc21, thanks so much for catching this! However, I think you actually want to use `DoubleChevronUp` in place of `chevronsUp`, and `DoubleChevronDown` in place of `chevronsDown` since those are the proper replacements for those metaphors. Once you make those changes, I'm happy to approve and merge this in.

**Comment by FSc21** [comment]
Sure, no problem :)

**Comment by battletoilet** [comment]
Approved

**Comment by Jahnp** [comment]
Approved

Thanks again @FSc21!

**Pull request merged**
